### ISSUE TITLE
Add Service to Service auth

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/megaphone#7]
The megaphone endpoint requires an auth check for both posting new broadcasts (from e.g. kinto, or AMO) and additionally for reading the current broadcasts (from generally only the autopush connection nodes).

Broadcasts contain a broadcasterID. Broadcasters should only be able to post new broadcasts under their specific broadcasterID.

**Comment by rfk** [comment]
I sent a rambling email to @bbangert about this just now, but noting it here for consideration as well.  Since we're using Auth0 internally for some things already, it's probably worth looking at their API Authorization features to see if that has what we need:

  https://auth0.com/docs/api-auth
  https://auth0.com/docs/architecture-scenarios/application/server-api

**Comment by rfk** [comment]
From async discussions, it sounds like there are three ways we could proceed here:

* Build out a bit more "service token" functionality in FxA, and use that
* Use hosted "service token" functionality from Auth0 as described above
* Use a direct "api key" approach, where each client service registers a secret directly with megaphone

@bbangert @pjenvey do you have strong feelings about what the right may to move forward is here?

**Comment by bbangert** [comment]
Per @jvehent's suggestion, we'll use a basic Authentication token that can be configured in the config/environment so that ops can update them as needed.
